services:
  - type: web
    name: inventory-system
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn inventory_system.wsgi:app"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: inventory-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true

databases:
  - name: inventory-db
    plan: free
